services:
  gui:
    image: bspsupsi/sleepyland:gui
    build:
      context: ./gui
    container_name: gui_container
    ports:
      - "8887:8887"
    depends_on:
      - manager-api
    volumes:
      - ./input:/app/input
      - ./output:/app/output

  manager-api:
    image: bspsupsi/sleepyland:manager-api
    build:
      context: ./manager-api
    container_name: manager_container
    ports:
      - "8989:8989"
    volumes:
      - ./input:/app/input
      - ./output:/app/output

  notebook:
    image: bspsupsi/sleepyland:notebook
    build:
      context: ./notebook
    container_name: notebook_container
    ports:
      - "8888:8888"
    volumes:
      - ./my-notebook:/app/my-notebook
      - ./input:/app/input
      - ./output:/app/output

  nsrr-download:
    image: bspsupsi/sleepyland:nsrr-download
    build:
      context: ./nsrr-download
    container_name: nsrr_download_container
    ports:
      - "8500:8500"
    volumes:
      - ./input:/app/input
      - ./output:/app/output

  usleepyland:
    image: bspsupsi/sleepyland:usleepyland
    build:
      context: ./usleepyland
    container_name: usleepyland_container
    ports:
      - "7777:7777"
    environment:
      - LD_PRELOAD=/opt/conda/envs/u-sleepyland-tfcuda/lib/libgomp.so.1:/opt/conda/envs/u-sleepyland-tfcuda/lib/python3.9/site-packages/sklearn/utils/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0
    volumes:
      - ./input:/app/input
      - ./output:/app/output

  wild-to-fancy:
    image: bspsupsi/sleepyland:wild-to-fancy
    build:
      context: wild-to-fancy
    container_name: wild_to_fancy_container
    ports:
      - "6666:6666"
    volumes:
      - ./input:/app/input
      - ./output:/app/output

volumes:
  my-notebook:
  input:
  output:
